### PR TITLE
Azure AD group members adapter

### PR DESCRIPTION
**Pull request by chris-brindley**
This PR adds a new adapter for Azure AD that enables syncing users to an AD group.

### CODE REVIEW

**Comment by chris-brindley** [comment]
Looks like the linter is failing some of the auto-generated mock code. Specifically `gci` is missing the `--skip-generated` flag.

I can fix the generated code but that feels like a smell to me. I think it's probably a good idea to ignore anything auto-generated with the linting instead - thoughts @jlucktay @mike-gregory-ovo ?

**Comment by jlucktay** [comment]
> Looks like the linter is failing some of the auto-generated mock code. Specifically `gci` is missing the `--skip-generated` flag.
> 
> I can fix the generated code but that feels like a smell to me. I think it's probably a good idea to ignore anything auto-generated with the linting instead - thoughts @jlucktay @mike-gregory-ovo ?

This looks like the same issue that causes the generated code to constantly fall out of alignment on the O2B tooling repo. If so, I think it's the Makefile targets being run in the wrong order.
The `lint-fix` target is already in there to straighten things like this out, so the dependencies just need a bit of rearranging. I'll make a branch and try to remedy it.

**Comment by jlucktay** [comment]
@chris-brindley #236 should sort it.

**Comment by chris-brindley** [comment]
@mike-gregory-ovo I think this PR is ready for a review following the fix @jlucktay implemented in the Makefile.

**Review by mike-gregory-ovo — APPROVED** [review]

**Pull request merged**
